/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.uport.vertx.auth.did;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
